name: Continuous Integration - Python Flask App

on:
  push:
    branches:
      - main
      - jenk  # Adjust branch names as needed
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest  # Replace with desired runner (e.g., macOS, Windows)

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'  # Specify desired Python version (e.g., 3.8, 3.9, 3.10)
          cache: 'pip'  # Cache dependencies for faster builds

      - name: Install dependencies
        run: pip install -r requirements.txt  # Replace with your requirements file path

      - name: List installed packages (optional)
        run: pip list

      - name: Run unit tests (adjust command based on your testing framework)
        run: echo "Tests to be added"  # Replace with your test discovery command

      - name: Build application (adjust command if building a specific output)
        run: python setup.py build  # Replace with your build command (e.g., pyinstaller)

      - name: Run linters or static code analysis (optional)
        run: |  # Example using Pylint
          pip install pylint
          pylint my_app.py  # Replace with your lint command and script name(s)

      - name: Upload build artifacts (optional)
        uses: actions/upload-artifact@v3
        with:
          name: built-app
          path: dist/  # Replace with your distribution directory